### ISSUE TITLE
Android Installation 

### ISSUE THREAD

**Issue by ilibilibom** [react-native-market/firebase-authentication-kit#1]
Hi
 I'm having trouble installing the authentication kit.

**Environment**
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 656.18 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Currently, I'm trying to run ```react-native run-android``` 

I've followed the read.md file instructions and did the following steps: 
1) Installed dependencies with yarn 
2) Run ```pod install --repo-update ``` within the iso folder (BTW - it asked me to upgrade the Firebase/Firestore package)
3) Generated a ketstore.debug file in the android folder
4) Run ```rename-script``` to my project name
5) Added the google-services.json to android folder
6) configured the facebook authentication

The error I'm getting when running  ```react-native run-android```  is: 
``` 
> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
135 actionable tasks: 3 executed, 132 up-to-date
/Users/ilandiamond/Developer/Code/ilan/segundo/segundoapp/android/app/src/main/java/com/segundo/firebaseauthkit/MainApplication.java:23: error: cannot find 
symbol
      return BuildConfig.DEBUG;
``` 

And here is the full log: 
``` warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-google-signin: https://github.com/react-native-community/react-native-google-signin
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1125 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...

> Configure project :@react-native-firebase_app
:@react-native-firebase_app:firebase.bom using default value: 21.1.0
:@react-native-firebase_app package.json found at my-path/Developer/Code/me/segundo/segundoapp/node_modules/@react-native-firebase/app/package.json
:@react-native-firebase_app:version set from package.json: 6.0.0 (6,0,0 - 6000000)
:@react-native-firebase_app:android.compileSdk using custom value: 28
:@react-native-firebase_app:android.targetSdk using custom value: 28
:@react-native-firebase_app:android.minSdk using custom value: 16
:@react-native-firebase_app:reactNativeAndroidDir my-path/Developer/Code/me/segundo/segundoapp/node_modules/react-native/android

> Configure project :@react-native-firebase_auth
:@react-native-firebase_auth:firebase.bom using default value: 21.1.0
:@react-native-firebase_auth package.json found at /my-path/Developer/Code/me/segundo/segundoapp/node_modules/@react-native-firebase/auth/package.json
:@react-native-firebase_auth:version set from package.json: 6.0.0 (6,0,0 - 6000000)
:@react-native-firebase_auth:android.compileSdk using custom value: 28
:@react-native-firebase_auth:android.targetSdk using custom value: 28
:@react-native-firebase_auth:android.minSdk using custom value: 16
:@react-native-firebase_auth:reactNativeAndroidDir /my-path/Developer/Code/me/segundo/segundoapp/node_modules/react-native/android

> Configure project :@react-native-firebase_firestore
:@react-native-firebase_firestore:firebase.bom using default value: 21.1.0
:@react-native-firebase_firestore package.json found at /my-path/Developer/Code/me/segundo/segundoapp/node_modules/@react-native-firebase/firestore/package.json
:@react-native-firebase_firestore:version set from package.json: 6.0.0 (6,0,0 - 6000000)
:@react-native-firebase_firestore:android.compileSdk using custom value: 28
:@react-native-firebase_firestore:android.targetSdk using custom value: 28
:@react-native-firebase_firestore:android.minSdk using custom value: 16
:@react-native-firebase_firestore:reactNativeAndroidDir /my-path/Developer/Code/me/segundo/segundoapp/node_modules/react-native/android

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :react-native-firebase
react-native-firebase: using React Native prebuilt binary from /my-path/Developer/Code/me/segundo/segundoapp/node_modules/react-native/android

> Task :app:processDebugGoogleServices
Parsing json file: /my-path/Developer/Code/me/segundo/segundoapp/android/app/google-services.json

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
135 actionable tasks: 3 executed, 132 up-to-date
/my-path/Developer/Code/me/segundo/segundoapp/android/app/src/main/java/com/segundo/firebaseauthkit/MainApplication.java:23: error: cannot find 
symbol
      return BuildConfig.DEBUG;
             ^
  symbol: variable BuildConfig
Note: /my-path/Developer/Code/me/segundo/segundoapp/android/app/src/main/java/com/segundo/firebaseauthkit/MainApplication.java uses or overrides
 a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/my-path/Developer/Code/me/segundo/segundoapp/android/app/src/main/java/com/segundo/firebaseauthkit/MainApplication.java:23: error: cannot find symbol
      return BuildConfig.DEBUG;
             ^
  symbol: variable BuildConfig
Note: /my-path/Developer/Code/me/segundo/segundoapp/android/app/src/main/java/com/segundo/firebaseauthkit/MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/my-path/Developer/Code/me/segundo/segundoapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/my-path/Developer/Code/me/segundo/segundoapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/my-path/Developer/Code/me/segundo/segundoapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7) ```

My Setup : macOS

**Comment by Ehesp** [comment]
Thanks for posting your logs. Looks like there is an issue with the build with Gradle 6. Looking into it now for you.

**Comment by ilibilibom** [comment]
and BTW - this is the error I get when running pod install --repo-update: 
``` 
[!] CocoaPods could not find compatible versions for pod "Firebase/Firestore":
  In snapshot (Podfile.lock):
    Firebase/Firestore (= 6.5.0, ~> 6.5.0)

  In Podfile:
    RNFBFirestore (from `../node_modules/@react-native-firebase/firestore`) was resolved to 6.0.0, which depends on
      Firebase/Firestore (~> 6.8.1)


You have either:
 * changed the constraints of dependency `Firebase/Firestore` inside your development pod `RNFBFirestore`.
   You should run `pod update Firebase/Firestore` to apply changes you've made.
```

**Comment by Salakar** [comment]
I've published a new version (0.0.02) of the product, if you can; please try it out - you can download it in your account purchases section on the website. Thanks

**Comment by ilibilibom** [comment]
Hi @Salakar 
0.0.2 Android build still fails. 
This is the error I get: 
``` 
* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.segundo.app signatures do not match previously installed version; ignoring! 
```

**Comment by Ehesp** [comment]
@ilibilibom on your emulator, please uninstall any previous React Native apps. That error means it was installing on device, but found another app with the same ID (so couldn't install).
